version: "3.8"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    #    restart: always
    environment:
      POSTGRES_USER: <your-database-username>
      POSTGRES_PASSWORD: <your-database-password>
      POSTGRES_DB: <your-database-name>
    ports:
      - "5432:5432"
    networks:
      - spring-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8888:8888"
    #    restart: always
    depends_on:
      - postgres
    networks:
      - spring-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/<your-database-name>
      SPRING_DATASOURCE_USERNAME: <your-database-username>
      SPRING_DATASOURCE_PASSWORD: <your-database-password>

volumes:
  postgres-data:

networks:
  spring-postgres:
